### ISSUE TITLE
Segfault when linearly indexing a sparse matrix

### ISSUE THREAD

**Issue by cuihantao** [sanurielf/kvxopt#4]
MWE:

```python
from kvxopt import spdiag, matrix

c = spdiag(matrix(range(1,1000)))
c[0:10000:30]
```

Segfaults on Python 3.9.7 on Ubuntu 20.04. KVXOPT version is 1.2.7.3. The code works fine with CVXOPT 1.2.7.

**Comment by sanurielf** [comment]
Let me take a look. The same happens in OSx and Python 3.9.9

**Comment by sanurielf** [comment]
Hi,

Kvxopt 1.2.7.4 (just released) includes the fix.
