### ISSUE TITLE
Version 1.2.7.5 for Linux and Windows not yet available in conda-forge

### ISSUE THREAD

**Issue by christian-cahig** [sanurielf/kvxopt#6]
Hi, I'm just curious as to why version 1.2.7.5 is, as of writing, only available for OSX ARM64.

**Comment by sanurielf** [comment]
Hi, version 1.2.7.5 is available for all the platforms. The webpage of conda forge is not updating well the releases but you can install v1.2.7.5 in either windows/linux

![image](https://user-images.githubusercontent.com/3075710/153719983-1413290a-3d55-42af-bff8-17900e07cd59.png)

**Comment by christian-cahig** [comment]
Thank you, @sanurielf.
