### ISSUE TITLE
Wheels for Linux aarch64

### ISSUE THREAD

**Issue by CarolusVitalis** [sanurielf/kvxopt#7]
This is a tremendous project, it solved the problem I was having with my Apple M1 processor.
However, I have run into a problem when generating a Docker image. The image creation fails when adding this package, as it does not have wheels for Linux ARM. Is there a possibility to add wheels for Linux aarch64?

**Comment by sanurielf** [comment]
Thanks! Sure, i will try to include it in this week. In the meantime you can try to install it using conda. I did include linux arm in the last update on conda builds.

**Comment by sanurielf** [comment]
https://anaconda.org/conda-forge/kvxopt

**Comment by sanurielf** [comment]
Hi @CarolusVitalis ,

The wheels for aarch64 are now available. Unfortunately, due to compiling time restrictions in a virtualized ARM container, I could not include GSL and GLPK extensions. Could you please test it and give us feedback?
